# Generated by Django 2.2.14 on 2021-06-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liaisons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsystemcd', models.CharField(max_length=20, verbose_name='系统名称')),
                ('fprojectcd', models.CharField(max_length=20, verbose_name='项目名称')),
                ('fslipno', models.CharField(db_index=True, max_length=20, verbose_name='联络票号')),
                ('ftype', models.CharField(max_length=10, verbose_name='类型')),
                ('fstatus', models.CharField(max_length=15, verbose_name='状态')),
                ('fodrno', models.CharField(db_index=True, max_length=20, verbose_name='订单号')),
                ('fcreatedte', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fcreateusr', models.CharField(max_length=24, verbose_name='创建者')),
                ('fassignedto', models.CharField(db_index=True, max_length=60, verbose_name='对应者')),
                ('fhelper', models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='协助者')),
                ('fleader', models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='负责人')),
                ('fbrief', models.TextField(verbose_name='开发描述')),
                ('fcontent', models.TextField(blank=True, null=True, verbose_name='问题描述')),
                ('fanalyse', models.TextField(blank=True, null=True, verbose_name='问题分析')),
                ('fsolution', models.TextField(blank=True, null=True, verbose_name='解决方案')),
                ('fplnstart', models.DateField(verbose_name='计划开始日期')),
                ('fplnend', models.DateField(verbose_name='计划结束日期')),
                ('factstart', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('factend', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('freleasedt', models.DateField(blank=True, null=True, verbose_name='程序发布日期')),
                ('fplnmanpower', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='预计工数')),
                ('factmanpower', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='实际工数')),
                ('freleaserpt', models.CharField(blank=True, max_length=200, null=True, verbose_name='程序发布报告URL')),
                ('fsirno', models.CharField(blank=True, max_length=10, null=True, verbose_name='SIR号')),
                ('forganization', models.IntegerField(blank=True, null=True, verbose_name='组织构架中组名')),
                ('fentdt', models.DateTimeField(auto_now_add=True, verbose_name='登入日期')),
                ('fentusr', models.CharField(blank=True, max_length=24, null=True, verbose_name='登录者')),
                ('fupdtedt', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日期')),
                ('fupdteusr', models.CharField(blank=True, max_length=24, null=True, verbose_name='更新者')),
                ('fupdteprg', models.CharField(blank=True, max_length=110, null=True, verbose_name='更新程序名')),
            ],
            options={
                'verbose_name': '联络票',
                'verbose_name_plural': '联络票',
                'db_table': 'liaisonf',
            },
        ),
    ]
