# Generated by Django 2.2.14 on 2021-06-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fslipno', models.CharField(max_length=20, verbose_name='联络票号')),
                ('fobjectid', models.CharField(max_length=100, verbose_name='Review对象')),
                ('fcontent_text', models.TextField(default='', verbose_name='Review内容')),
                ('fentdt', models.DateField(auto_now_add=True, verbose_name='登入日期')),
                ('fentusr', models.CharField(blank=True, max_length=24, null=True, verbose_name='登录者')),
                ('fupdtedt', models.DateField(blank=True, null=True, verbose_name='更新日期')),
                ('fupdteusr', models.CharField(blank=True, max_length=24, null=True, verbose_name='更新者')),
                ('fupdteprg', models.CharField(blank=True, max_length=110, null=True, verbose_name='更新程序名')),
            ],
            options={
                'verbose_name': '设计or代码Review',
                'verbose_name_plural': '设计or代码Review',
                'db_table': 'codereview',
            },
        ),
    ]
